name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build Debug Empty project
        run: cargo build --verbose --example blank
      - name: Build Release Empty project
        run: cargo build -r --verbose --example blank

      - name: Build Debug Basic project
        run: cargo build --verbose --example cube
      - name: Build Release Basic project
        run: cargo build -r --verbose --example cube

      - name: Build Debug Maze
        run: cargo build --verbose --example maze
      - name: Build Release Maze
        run: cargo build -r --verbose --example maze

      - name: Build Debug Sail
        run: cargo build --verbose --example sail
      - name: Build Release Sail
        run: cargo build -r --verbose --example sail

      - name: Run tests
        run: cargo test --verbose
