name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build Debug
        run: cargo build --verbose --example maze
      - name: Build Release
        run: cargo build -r --verbose --example maze
      - name: Run tests
        run: cargo test --verbose
